name: Add PR to Project Item
on:
  pull_request:
    branches: [ main ]

jobs:
  addItem:
    runs-on: ubuntu-latest
    name: A job to send slack alert when PR is opened
    steps:
      - name: 'Dump github content'
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash

      - name: 'Get Jira Number'
        run: echo 'Every repo can have its own logic for getting jira Number from repo'

      - name: 'Pull Jira information'
        env:
            JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
        run: |
          curl --location --request GET 'https://jira.nutanix.com/rest/api/latest/issue/SAAS-20750' --header "Authorization: Bearer $JIRA_TOKEN" > jira.json
          echo 'JIRA_STATUS='$(jq '.fields.status.name' project_data.json) >> $GITHUB_ENV
          echo 'JIRA_SPRINT='$(jq '.fields.customfield_10360[0]' | sed -e 's/.*name=//' -e 's/,.*//' project_data.json) >> $GITHUB_ENV

      - name: Print Jira information
        run: echo "The output was $JIRA_STTAUS and $JIRA_SPRINT"