name: Add PR to Project Item
'on':
  pull_request:
    branches:
      - main
jobs:
  addItem:
    runs-on: ubuntu-latest
    name: A job to open Project Item when PR is raised
    steps:
      - name: Dump github content
        run: 'echo ''${{ toJSON(github.event) }}'' | jq'
        shell: bash
      - name: Get Jira Number
        run: >-
          echo 'Every repo can have its own logic for getting jira Number from
          repo'
      - name: Print Secret
        env:
          JIRA_TOKEN: '${{ secrets.JIRA_TOKEN }}'
        run: echo ${{ env.JIRA_TOKEN }}
      - name: Pull Jira information
        env:
          JIRA_TOKEN: '${{ secrets.JIRA_TOKEN }}'
        run: |
          curl -X GET 'https://jira.nutanix.com/rest/api/latest/issue/SAAS-20750' -H "Authorization: Bearer MDMyMTg1MjI0Mjk1OmfTUtfG+aYWL8T8VLkspbzm/puu" | jq
      - name: Print Jira information
        run: echo "The output was $JIRA_STTAUS and $JIRA_SPRINT"
