name: SCoRe
on:
  push:
    branches: [Nitin-test]
  pull_request:
    branches: [ main ]
jobs:
  auto-fix: 
    runs-on: ubuntu-latest
    name: Auto Fix
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm install
    - name: Get Config
      run: |
        ESLINT=$(curl -L 'https://api.npoint.io/2275cfec5ddfc130b1a1/Test%20Repo' | jq '.codeFixerOptions.eslint')
        echo "ESLINT=$ESLINT" >> $GITHUB_ENV
        echo "::set-env ESLINT=$ESLINT"
        FORMATTER=$(curl -L 'https://api.npoint.io/2275cfec5ddfc130b1a1/Test%20Repo' | jq '.codeFixerOptions.formatter')
        echo "FORMATTER=$FORMATTER" >> $GITHUB_ENV
        echo "::set-env FORMATTER=$FORMATTER"
    - name: Lint & fix
      if: ${{ env.ESLINT == 'true' }}
      run: npx eslint . --fix --ext .js --config .eslintrc
    - name: Formatter & fix
      if: ${{ env.FORMATTER == 'true' }}
      run: npx eslint . --fix --ext .js --no-eslintrc --config .eslintrc-formatter
    - name: Create Pull Request
      if: ${{ env.ESLINT == 'true' || env.FORMATTER == 'true' }}
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.AUTOFIX }}
        base: ${{ github.head_ref }}
        branch: ${{ github.head_ref }}-autofix
        commit-message: "Automated eslint fixes"
        reviewers: ${{ github.actor }}
        labels: autofix
        delete-branch: true
        title: "Auto Fix: \"${{ github.event.pull_request.title }} (#${{github.event.pull_request.number}})\" "
        body: |
            Automated PR to improve codestyle
            - Base PR ${{github.event.pull_request.html_url}}
