name: Auto Fix
on:
  push:
    branches: [testpy]
  pull_request:
    branches: [ main1 ]
jobs:
  auto-fix: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: pip install black flake8
    - name: Get Config
      run: |
        ESLINT=$(curl -L 'https://api.npoint.io/2275cfec5ddfc130b1a1/Test%20Repo' | jq '.codeFixerOptions.eslint')
        echo "ESLINT=$ESLINT" >> $GITHUB_ENV
        echo "::set-env ESLINT=$ESLINT"
        FORMATTER=$(curl -L 'https://api.npoint.io/2275cfec5ddfc130b1a1/Test%20Repo' | jq '.codeFixerOptions.formatter')
        echo "FORMATTER=$FORMATTER" >> $GITHUB_ENV
        echo "::set-env FORMATTER=$FORMATTER"
    - name: Run linters
      uses: wearerequired/lint-action@v2
      with:
        auto_fix: true
        black: true
        black_auto_fix: true
        flake8: true
        flake8_auto_fix: false
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.AUTOFIX }}
        base: ${{ github.head_ref }}
        branch: ${{ github.head_ref }}-autofix
        commit-message: "Automated eslint fixes"
        reviewers: ${{ github.actor }}
        labels: autofix
        delete-branch: true
        title: "Auto Fix: \"${{ github.event.pull_request.title }} (#${{github.event.pull_request.number}})\" "
        body: |
            Automated PR to improve codestyle
            - Base PR ${{github.event.pull_request.html_url}}
