name: Fetch Jira Story Details from Git Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  fetch-jira-story-details:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install dependencies
        run: |
          npm install
          pip install -r requirements.txt
      - name: Fetch Jira Story Details
        env:
          JIRA_USER: pratikjagtap010@gmail.com
          JIRA_API_TOKEN: ATATT3xFfGF0T8TEJBxblfpPlPgwOkdG66PG42HPBo9ZePDHIFqvUpupG5DLoDZi3b25rg9p8eDZh61lQS7FJ8muKiMhMXIrUIE1W5QIW3UnN-KAmRxV2xlBWocyekPRh6ObpRGTYKIa96PWlYBcCJv-5E4_t4OJh6Zp3pk12rJUpq19wg4pzKA=AF8FACEB
          JIRA_URL: https://hackthon.atlassian.net
        run: |
          python fetch_jira_story_details.py
