name: JIRA Story Details from Git Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  jira_story_details:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install JIRA CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -L "https://github.com/clearvision/jira-cli/releases/download/3.9.0/jira-linux-amd64" -o /usr/local/bin/jira
          chmod +x /usr/local/bin/jira
      
      - name: Fetch JIRA Story Details
        run: |
        fetch(https://hackthon.atlassian.net/rest/api/latest/issue/${{ toJSON(github.event.pull_request.head.ref) }})
          .then(response => response.json())
          .then(jsonData => console.log(jsonData))
       

    # steps:
    #   - name: 'Dump github content'
    #     run: echo 'branch name ${{ toJSON(github.event.pull_request.head.ref) }}' | jq
    #     shell: bash

