name: Update Jira Status on Pull Request

on:
  pull_request:
    types: [opened, reopened]

env:
  JIRA_API_TOKEN: ATATT3xFfGF0T8TEJBxblfpPlPgwOkdG66PG42HPBo9ZePDHIFqvUpupG5DLoDZi3b25rg9p8eDZh61lQS7FJ8muKiMhMXIrUIE1W5QIW3UnN-KAmRxV2xlBWocyekPRh6ObpRGTYKIa96PWlYBcCJv-5E4_t4OJh6Zp3pk12rJUpq19wg4pzKA=AF8FACEB
  JIRA_USERNAME: pratik jagtap
  JIRA_URL: 'https://hackthon.atlassian.net'

jobs:
  update_jira_status:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Update Jira Status
      uses: atlassian/gajira-transition@v1
      with:
        api_token: ATATT3xFfGF0T8TEJBxblfpPlPgwOkdG66PG42HPBo9ZePDHIFqvUpupG5DLoDZi3b25rg9p8eDZh61lQS7FJ8muKiMhMXIrUIE1W5QIW3UnN-KAmRxV2xlBWocyekPRh6ObpRGTYKIa96PWlYBcCJv-5E4_t4OJh6Zp3pk12rJUpq19wg4pzKA=AF8FACEB
        jira_url: https://hackthon.atlassian.net/rest/api/latest/issue
        username: pratik jagtap
        issue_key: ${{ github.event.pull_request.head.ref }}
        transition_name: 'In Progress'
