name: npm audit

on:
  push:
    branches: [Nitin-test]
  pull_request:
    branches: [ main, dev ]

jobs:
  scan:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - uses: oke-py/npm-audit-action@v2
        with:
          audit_level: moderate
          github_token: ${{ secrets.AUTOFIX }}
          issue_labels: vulnerability
          dedupe_issues: true
