name: Check if other PRs can be merged
on:
  pull_request:
    types: [review_requested, review_request_removed]
jobs:
  track_pr:
    runs-on: ubuntu-latest
    steps:
      - name: 'Dump github content'
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name: 'Pull all PRs that are in open state against main branch'
        env:
          USER: rdhar8
          REPO: sample-code
          PROJECT_NUMBER: 1
        run: |
          gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${{ env.USER }}/${{ env.REPO }}/pulls | jq