name: SCoRe
on:
  push:
    branches: [ Nitin-test ]
  pull_request:
    branches: [ main, score_scan ]
jobs:
  njsscan:
    runs-on: ubuntu-latest
    name: Security Scan
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: nodejsscan scan
      id: njsscan
      uses: ajinabraham/njsscan-action@master
      with:
        args: '.'
