name: Sends Slack alert when PR is assigned
on:
  pull_request:
    types: [review_requested]
jobs:
  track_pr:
    runs-on: ubuntu-latest
    steps:
      - name: 'Dump github content'
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash

      - name: Invoke Action to send alert
        id: slack
        uses: raveesh-mittal/code-reviewer@v1.3.7
        with:
          is-pull-request-opened: true
          github-token:  ${{ secrets.PR_TOKEN }}
          slack-token: ${{ secrets.SLACK_TOKEN }}
          slack-channel: 'U051FP02KF1'
          data: ${{ github.event.pull_request.self}}